In [24]:
import tensorflow as tf

# Constantes

In [7]:
valor1 = tf.constant(2, name='valor_1')
valor2 = tf.constant(3)

In [13]:
valor1

<tf.Tensor 'valor_1:0' shape=() dtype=int32>

Essa operação abaixo não retorna nada. Isso é basicamente a criação de um grafo que representa a soma de dois inputs

In [10]:
soma = valor1 + valor2

In [14]:
soma

<tf.Tensor 'add:0' shape=() dtype=int32>

Para rodar algo no TF, devemos inicializar uma Seção.

In [15]:
with tf.Session() as sess:
    s = sess.run(soma)

Rodada a seção, podemos ver o resultado da `soma`

In [18]:
print(s)

5


In [19]:
texto1 = tf.constant('texto 1')
texto2 = tf.constant('texto 2')

In [21]:
texto1

<tf.Tensor 'Const_4:0' shape=() dtype=string>

In [22]:
with tf.Session() as sess:
    concatenacao = sess.run(texto1 + texto2)

In [25]:
concatenacao

b'texto 1texto 2'

# Variáveis

In [27]:
constante1 = tf.constant(15)
constante1

<tf.Tensor 'Const_7:0' shape=() dtype=int32>

Definição da formula para um grafo específico

In [29]:
soma = tf.Variable(constante1 + 5, name='soma1')
soma

<tf.Variable 'soma1:0' shape=() dtype=int32_ref>

Quando utilizamos variáveis, devemos utilizar um comando especial. Caso não utilizamos, o seguinte erro é apresentado

```python

FailedPreconditionError: Attempting to use uninitialized value soma1

    ```

In [32]:
init = tf.global_variables_initializer()

In [33]:
with tf.Session() as sess:
    sess.run(init)
    s=sess.run(soma)

In [34]:
s

20

# Mais variáveis

In [35]:
vetor = tf.constant([5,10,15], name='vetor')
vetor

<tf.Tensor 'vetor:0' shape=(3,) dtype=int32>

In [36]:
soma = tf.Variable(vetor + 5, name='soma')

Soma parecida com a do numpy

In [37]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(soma))

[10 15 20]


In [42]:
variavel1 = tf.Variable(0, name='valor')
init2 = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init2)
    for i in range(5):
        variavel1 = variavel1 + 1
        print(sess.run(variavel1))

1
2
3
4
5


# Operações de Vetores e Matrizes

In [43]:
a = tf.constant([10, 20, 30], name='vetorA')
b = tf.constant([5, 20, 35], name='vetorB')

In [45]:
soma = a + b
soma

<tf.Tensor 'add_21:0' shape=(3,) dtype=int32>

In [46]:
with tf.Session() as sess:
    print(sess.run(soma))

[15 40 65]


## Soma de Vetores de tamanhos diferentes

In [48]:
a = tf.constant([10, 20, 30, 40], name='vetorA')
b = tf.constant([5, 20, 35], name='vetorB')

```python
soma = a + b

ValueError: Dimensions must be equal, but are 4 and 3 for 'Add') with input shapes: [4], [3].
```

In [69]:
matrix_a = tf.constant([[1,2,3],[4,5,6]],name='matrixb')
matrix_a

<tf.Tensor 'matrixb_5:0' shape=(2, 3) dtype=int32>

In [70]:
matrix_b = tf.constant([[1,2,3],[4,5,6]],name='matrixb')

In [71]:
soma_m = tf.add(matrix_a, matrix_b)

In [72]:
with tf.Session() as sess:
    print(sess.run(soma_m))

[[ 2  4  6]
 [ 8 10 12]]


Multiplicação valor por valor dos elementos das matrizes

In [74]:
mult = tf.multiply(matrix_a, matrix_b)

In [64]:
with tf.Session() as sess:
    print(sess.run(mult))

[[ 1  4  9]
 [16 25 36]]


## Multiplicação REAL das matrizes:



Tf dá erro caso vc tente multiplicar matrixes que não são passíveis de multiplicação:

```python
InvalidArgumentError: Dimensions must be equal, but are 3 and 2 for 'MatMul_4' (op: 'MatMul') with input shapes: [2,3], [2,3].


```

In [75]:
matrix_a = tf.constant([[1,2,3],[4,5,6]],name='matrixa')
matrix_b = tf.constant([[1,2,3],[4,5,6],[7,8,9]],name='matrixb')

# mxa = 2x3 e mxb = 3,3 (Passivel de ser multiplicado)
mult = tf.matmul(matrix_a, matrix_b)
with tf.Session() as sess:
    print(sess.run(mult))

[[30 36 42]
 [66 81 96]]


## Produto Escalar

In [81]:
matrix_a = tf.constant([[-1, 7, 5]], dtype=tf.float32, name='inputs')
matrix_b = tf.constant([[0.8, 0.1, 0.0]], dtype=tf.float32, name='pesos')

multiplicacao = tf.multiply(matrix_a, matrix_b)
soma = tf.reduce_sum(multiplicacao)


with tf.Session() as sess:
    print(sess.run(soma))

-0.100000024


In [87]:
matrix_a = tf.constant([[-1, 7, 5]], dtype=tf.float32, name='inputs')
matrix_b = tf.constant([[0.8, 0.1, 0.0]], dtype=tf.float32, name='pesos')

dot = tf.tensordot(matrix_a, matrix_b, 1)


with tf.Session() as sess:
    print(sess.run(dot))

[[[[-0.8 -0.1  0. ]]

  [[ 5.6  0.7  0. ]]

  [[ 4.   0.5  0. ]]]]
