In [1]:
import tensorflow as tf

# Placeholder

é uma variável que atribuimos dados

In [19]:
placeholder_a = tf.placeholder(tf.float32, None) # Args: Tipo dos dados, Dimensão (shape)
placeholder_a

<tf.Tensor 'Placeholder_5:0' shape=<unknown> dtype=float32>

In [20]:
operacao = tf.add(placeholder_a,2)

Caso tente rodar `operacao` no session o seguinte erro aparecerá:

```python

with tf.Session() as sess:
    print(sess.run(operacao))

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
```

In [21]:
with tf.Session() as sess:
    resultado = sess.run(operacao, feed_dict={
        placeholder_a:[1,2,3,4]
    })
    print(resultado)

[3. 4. 5. 6.]


In [24]:
placeholder_a = tf.placeholder(tf.float32, [None, 3]) # entrada: [N linhas, 3 colunas]
placeholder_a

operacao = tf.pow(placeholder_a, 2)


with tf.Session() as sess:
    resultado = sess.run(operacao, feed_dict={
        placeholder_a:[[1,2,3], [12,23,33], [11,22,33], [112,232,344]]
    })
    print(resultado)

[[1.00000e+00 4.00000e+00 9.00000e+00]
 [1.44000e+02 5.29000e+02 1.08900e+03]
 [1.21000e+02 4.84000e+02 1.08900e+03]
 [1.25440e+04 5.38240e+04 1.18336e+05]]
